### ISSUE TITLE
Carla Integration

### ISSUE THREAD

**Issue by melihyazgan** [ms-van3t-devs/ms-van3t#12]
Greetings,

I would like to ask if anyone in the community integrated or tested the usage of repo in Carla environment with Sumo and ROS?

Regards,
Melih

**Comment by carlosrisma** [comment]
Dear Melih,

to the best of our knowledge, there are no public projects that have combined ms-van3t (nor ns-3) and CARLA with SUMO and ROS. 
However, we are pleased to tell you that we have just released the first version of our new extension ms-van3t-CARLA which combines all features of ms-van3t with mobility and sensor perception simulation of CARLA, leveraging the OpenCDA framework.
Our solution integrates ns-3 and CARLA directly, without SUMO or ROS, and hopefully, it can help your needs.

Best regards,
Carlos

**Comment by melihyazgan** [comment]
Hi Carlos,

I just read the paper. Thank you for your effort. It seems promising. I will give it a try. I hope I can further improve for myself and contribute even in open source.

Regards,
Melih
